---
title: "Exercise 3.2"
subtitle: "Anticipated Productivity Shocks"
---
<a class="return-button" href="index.qmd">⬅ Return</a>

## Problem

Consider a perfect-foresight economy populated by a large number of identical households with preferences described by the utility function

$$
\sum_{t=0}^{\infty} \beta^t U(c_t),
$$

where $c_t$ denotes consumption, $U$ is a period utility function assumed to be strictly increasing, strictly concave, and twice continuously differentiable, and $\beta \in (0, 1)$ is a parameter denoting the subjective rate of discount. Households are subject to the following four constraints:

$$
y_t + d_t = (1 + r)d_{t-1} + c_t + i_t,
$$

$$
y_t = A_t F(k_t),
$$

$$
k_{t+1} = k_t + i_t,
$$

$$
\lim_{j \to \infty} \frac{d_{t+j}}{(1 + r)^j} \leq 0,
$$

given $d_{-1}$, $k_0$, and $\{A_t\}_{t=0}^{\infty}$. The variable $d_t$ denotes holdings of one-period external debt at the end of period $t$, $r$ denotes the interest rate on these debt obligations, $y_t$ denotes output, $k_t$ denotes the (predetermined) stock of physical capital in period $t$, and $i_t$ denotes gross investment. $F$ is a production function assumed to be strictly increasing, strictly concave, and to satisfy the Inada conditions, and $A_t > 0$ is an exogenous productivity factor. Suppose that $\beta(1 + r) = 1$. Assume further that up until period $-1$ inclusive, the productivity factor was constant and equal to $\bar{A} > 0$ and that the economy was in a steady state with a constant level of capital and a constant net debt position equal to $\bar{d}$. Suppose further that in period 0 the productivity factor also equals $\bar{A}$, but that agents learn that in period 1 it will jump permanently to $A' > \bar{A}$. That is, in period 0, households know that the path of the productivity factor is given by:

$$
A_t = 
\begin{cases}
\bar{A} & t \leq 0 \\
A' > \bar{A} & t \geq 1
\end{cases}
$$

1. Characterize the equilibrium paths of output, consumption, investment, capital, the net foreign debt position, the trade balance, and the current account.

2. Compare your answer to the case of an unanticipated permanent increase in productivity studied in section 3.3.

3. Now assume that the anticipated productivity shock is transitory. Specifically, assume that the information available to households at $t = 0$ is

    $$
    A_t =
    \begin{cases}
    \bar{A} & t \leq -1 \\
    \bar{A} & t = 0 \\
    A' > \bar{A} & t = 1 \\
    \bar{A} & t \geq 2
    \end{cases}
    $$

    (a) Characterize the equilibrium dynamics.

    (b) Compare your answer to the case of an unanticipated temporary increase in productivity studied in section 3.4.

    (c) Compare your answer to the case of an anticipated transitory endowment shock in the
endowment economy studied in exercise 2.5 of chapter 2.

## Answer

#### 1.

From the equilibrium condition $k_{t+1} = \kappa\left(\frac{A_{t+1}}{r}\right)$, we have that

$$
k_t = \bar{k} \equiv \kappa\left( \frac{\bar{A}}{r} \right) \quad \text{for } t \leq 0,
$$

and

$$
k_t = k' \equiv \kappa\left( \frac{A'}{r} \right) \quad \text{for } t > 0.
$$

So we have that

$$
k_t =
\begin{cases}
\bar{k} & t < 0 \\
\bar{k} & t = 0 \\
k' > \bar{k} & t > 0
\end{cases}
$$

$$
i_t =
\begin{cases}
0 & t < 0 \\
k' - \bar{k} > 0 & t = 0 \\
0 & t > 0
\end{cases}
$$

$$
y_t =
\begin{cases}
\bar{A}F(\bar{k}) & t < 0 \\
\bar{A}F(\bar{k}) & t = 0 \\
A'F(k') > \bar{A}F(\bar{k}) & t > 0
\end{cases}
$$

From the intertemporal resource constraint and the fact that $c_t = c_0$ for all $t$ we have that

$$
\begin{aligned}
rd_{-1} + c_0 &= \frac{r}{1 + r} \sum_{t=0}^{\infty} \left( \frac{1}{1 + r} \right)^t \left[ A_t F(k_t) - (k_{t+1} - k_t) \right] \\
&= \frac{r}{1 + r} \left[ \bar{A} F(\bar{k}) - (k' - \bar{k}) + r^{-1} A' F'(k') \right] \\
&= \bar{A} F(\bar{k}) + \frac{r}{1 + r} \left[ -r^{-1} \bar{A} F(\bar{k}) + r^{-1} A' F'(k') - (k' - \bar{k}) \right] \\
&= rd_{-1} + c_{-1} + \frac{1}{1 + r} \left[ A' F(\bar{k}) - \bar{A} F(\bar{k}) + A' F(k') - A' F(\bar{k}) - r(k' - \bar{k}) \right] \\
&= rd_{-1} + c_{-1} + \frac{1}{1 + r} \left[ A' F(k') - \bar{A} F(\bar{k}) + A' F'(k') - A' F(\bar{k}) - A' F'(k') (k' - \bar{k}) \right] \\
&\geq rd_{-1} + c_{-1},
\end{aligned}
$$

where the last equality uses the fact that $r = A' F'(k')$, and the inequality uses the fact that by the mean value theorem $A' F(k') - A' F(\bar{k}) - A' F'(k')(k' - \bar{k}) > 0$. We then have that

$$
c_0 > c_{-1},
$$

that is, consumption jumps up in period 0 and stays at that higher level thereafter.

The trade balance deteriorates in period 0. To see this, write

$$
tb_0 - tb_{-1} = (y_0 - y_{-1}) - (c_0 - c_{-1}) - (i_0 - i_{-1})
$$

and note that $y_0 - y_{-1} = 0$, $c_0 - c_{-1} > 0$, and $i_0 - i_{-1} = i_0 > 0$. Let $tb_0 = tb'$. In period 1, the trade balance improves, because output increases, consumption doesn’t change, and investment drops to zero. We have already shown that output, consumption, and investment are all constant from period 1 on. This implies that the trade balance is also constant from period 1 on. Let $tb_t = tb''$ for $t \geq 1$. We have established that $tb'' > tb' > tb_{-1} = rd_{-1}$. Summarizing,

$$
tb_t =
\begin{cases}
rd_{-1} & t < 0 \\
tb' < rd_{-1} & t = 0 \\
tb'' = rd_0 > rd_{-1} & t > 0
\end{cases}
\quad \tag{*}
$$


The last line will become clear shortly, when we characterize the equilibrium path of debt. It says that after deteriorating in period 0, the trade balance improves to a level higher than in the original steady state.


The stock of debt increases in period 0. To see this, write

$$
\begin{aligned}
d_0 &= (1 + r) d_{-1} - tb_0 \\
&= (1 + r) d_{-1} - tb_{-1} - (tb_0 - tb_{-1}) \\
&= d_{-1} - (tb_0 - tb_{-1}) \\
&> d_{-1}
\end{aligned}
$$

since $tb_0 - tb_{-1} < 0$. Because the trade balance is constant (and equal to $tb''$) from period 1 on, we have that the evolution of debt satisfies

$$
d_t = (1 + r) d_{t-1} - tb''; \quad t \geq 1
$$

The only nonexplosive solution to this expression is

$$
d_t = d_0; \quad t \geq 1
$$

which means that

$$
tb'' = r d_0 > r \bar{d}
$$

This explains the last line of (*). Summarizing,

$$
d_t =
\begin{cases}
\bar{d} & t < 0 \\
d' > \bar{d} & t = 0 \\
d'' > \bar{d} & t > 0
\end{cases}
$$

The current account, being the change in the stock of debt, is negative in period 0 and 0 thereafter,

$$
ca_t =
\begin{cases}
0 & t < 0 \\
-(d' - \bar{d}) < 0 & t = 0 \\
0 & t > 0
\end{cases}
$$

#### 2.

The key difference is that under a permanent but anticipated increase in productivity, output does not increase in period 0. This is because at $t = 0$ $A_t$ and $k_t$ are still at their old values $\bar{A}$ and $\bar{k}$. In the unanticipated case, by contrast, $A_0 = A' > \bar{A}$ and $k_0 = \bar{k}$, so output increases in period 0. Besides this, the two cases are similar in the sense that in period 0 consumption and investment increase, and the trade balance deteriorates.

#### 3.

##### (a)

From the equilibrium condition $k_{t+1} = \kappa(A_{t+1}/r)$, we have that $k_t = \bar{k} \equiv \kappa(\bar{A}/r)$ for $t \leq 0$, $k_1 = k' \equiv \kappa(A'/r)$, and $k_t = \bar{k}$ for $t > 1$. So we have that

$$
k_t =
\begin{cases}
\bar{k} & t < 0 \\
\bar{k} & t = 0 \\
k' > \bar{k} & t = 1 \\
\bar{k} & t > 1
\end{cases}
$$

$$
i_t =
\begin{cases}
0 & t < 0 \\
k' - \bar{k} > 0 & t = 0 \\
\bar{k} - k' < 0 & t = 1 \\
0 & t > 1
\end{cases}
$$

$$
y_t =
\begin{cases}
\bar{A}F(\bar{k}) & t < 0 \\
\bar{A}F(\bar{k}) & t = 0 \\
A'F(k') > y_0 & t = 1 \\
\bar{A}F(\bar{k}) & t > 1
\end{cases}
$$

From the intertemporal resource constraint and the fact that $c_t = c_0$ for all $t$ we have:

$$
\begin{aligned}
rd_{-1} + c_0 &= \frac{r}{1 + r} \sum_{t=0}^{\infty} \frac{A_t F(k_t) - (k_{t+1} - k_t)}{(1 + r)^t}\\
&= \frac{r}{1 + r} \left[ \left( \frac{1 + r}{r} \right) \bar{A}F(\bar{k}) + \frac{1}{1 + r}(A'F(k') - \bar{A}F(\bar{k})) - (k' - \bar{k}) + \frac{1}{1 + r}(k' - \bar{k}) \right]\\
&= \bar{A}F(\bar{k}) + \frac{r}{(1 + r)^2} \left[ A'F(k') - \bar{A}F(\bar{k}) - r(k' - \bar{k}) \right]\\
&= \bar{A}F(\bar{k}) + \frac{r}{(1 + r)^2} \left[ A'F(k') - \bar{A}F(\bar{k}) - A'F'(k')(k' - \bar{k}) \right]\\
&= rd_{-1} + c_{-1} + \frac{r}{(1 + r)^2} \left[ A'F(\bar{k}) - \bar{A}F(\bar{k}) + A'F(k') - A'F(\bar{k})- A'F'(k')(k' - \bar{k}) \right]\\
&> rd_{-1} + c_{-1}
\end{aligned}
$$

which implies that

$$
c_0 > c_{-1}
$$

that is, consumption jumps up in period 0 and stays at that higher level thereafter. Comparing this derivation with the one for an anticipated permanent productivity shock, it is clear that the increase in consumption is now smaller. The trade balance deteriorates in period 0. To see this, write

$$
tb_0 - tb_{-1} = (y_0 - y_{-1}) - (c_0 - c_{-1}) - (i_0 - i_{-1})
$$

and note that $y_0 - y_{-1} = 0$, $c_0 - c_{-1} > 0$, and $i_0 > 0$. The deterioration in the trade balance is smaller than in the case in which the anticipated productivity shock is permanent, because now the increase in consumption is smaller. In period 1 the trade balance improves:

$$
\begin{aligned}
tb_1 - tb_0 &= (y_1 - y_0) - (c_1 - c_0) - (i_1 - i_0) \\
&= A'F(k') - \bar{A}F(\bar{k}) + 2(k' - \bar{k}) \\
&> 0
\end{aligned}
$$

In period 2 the trade balance deteriorates because output falls from $A'F(k')$ to $\bar{A}F(\bar{k})$, and investment goes from negative to zero:

$$
\begin{aligned}
tb_2 - tb_1 &= (y_2 - y_1) - (c_2 - c_1) - (i_2 - i_1) \\
&= \bar{A}F(\bar{k}) - A'F(k') - (k' - \bar{k}) \\
&< 0
\end{aligned}
$$

As we will see shortly, the trade balance in period 2 is lower than in the original steady state. From period 2 on, output is constant and equal to $\bar{A}F(\bar{k})$, consumption is constant and equal to $c_0$, and investment is zero, so the trade balance is constant and equal to $\bar{A}F(\bar{k}) - c_0 < \bar{A}F(\bar{k}) - c_{-1} = tb_{-1} = r\bar{d}$. Summarizing,

$$
tb_t =
\begin{cases}
rd_{-1} & t < 0 \\
tb' < rd_{-1} & t = 0 \\
tb'' > tb' & t = 1 \\
rd_{-1} < tb'' & t > 1
\end{cases}
$$

The stock of debt increases in period 0. To see this, write

$$
\begin{aligned}
d_0 &= (1 + r)d_{-1} - tb_0 \\
&= (1 + r)d_{-1} - tb_{-1} - (tb_0 - tb_{-1}) \\
&= d_{-1} - (tb_0 - tb_{-1}) \\
&> d_{-1}
\end{aligned}
$$

since $tb_0 < tb_{-1}$. In period 1, debt falls to a level lower than in the original steady state. To see this, recall that the trade balance is constant from period 2 on, so the evolution of debt satisfies

$$
d_t = (1 + r)d_{t-1} - tb_2, \quad t \geq 2
$$

which means that the only nonexplosive solution is

$$
d_t = d_1 = tb_2 / r = (\bar{A}F(\bar{k}) - c_0)/r < (\bar{A}F(\bar{k}) - c_{-1})/r = tb_{-1}/r = d_{-1} = \bar{d},
$$

for $t \geq 1$. So we can write

$$
d_t =
\begin{cases}
\bar{d} & t < 0 \\
d' > \bar{d} & t = 0 \\
d'' < \bar{d} & t > 0
\end{cases}
$$

The current account, being the change in the stock of debt, is negative in period 0, positive in period 1, and 0 thereafter,

$$
ca_t =
\begin{cases}
0 & t < 0 \\
-(d' - \bar{d}) < 0 & t = 0 \\
-(d'' - d') > 0 & t = 1 \\
0 & t > 1
\end{cases}
$$

##### (b)

The key diﬀerence is in the trade balance and the current account. Both deteriorate when the temporary shock is anticipated but improve when it is unanticipated. This is primarily because in the former case in period 0 investment increases and output is unchanged, whereas in the latter case investment is unchanged and output increases.


##### (c)

An anticipated endowment shock would also cause a deterioration in the trade balance and the current account in period 0, because output is unchanged but consumption increases (as households feel richer). However, the deterioration in the external accounts is smaller, because in the economy with capital investment is a second source of increase in domestic absorption.

