---
title: "Exercise 2.14"
subtitle: "Leontief Preferences Over Discounted Period Utilities"
---
<a class="return-button" href="index.qmd">⬅ Return</a>

## Problem

Consider a perfect-foresight small open economy populated by a large number of identical households with preferences described by the utility function

$$
\min_{t \geq 0} \left\{ \beta^t c_t \right\},
$$

where $c_t$ denotes consumption in period $t$, and $\beta \in (0, 1)$ is a parameter. Households have access to the international financial market, where they can borrow or lend at the constant interest rate $r$. Assume that

$$
\beta(1 + r) = 1 + \gamma,
$$

where $\gamma > 0$ is a parameter. Households are endowed with a constant amount of consumption goods denoted by $y$ each period and start period 0 with a level of debt equal to $d_{-1} > 0$. Finally, households are subject to a no-Ponzi-game constraint of the form

$$
\lim_{t \to \infty}(1 + r)^{-t} d_t \leq 0,
$$

where $d_t$ denotes one-period debt acquired in period $t$ and maturing in $t+1$.

1. Formulate the household’s maximization problem.

2. Write down the complete set of optimality conditions.

3. Characterize the equilibrium paths of consumption and debt in this economy. In particular, express the equilibrium levels of $c_t$ and $d_t$, for $t \geq 0$, in terms of the structural parameters (possibly $\beta$, $r$, $\gamma$, and $y$) and the initial condition $d_{-1}$.

4. What is the equilibrium asymptotic growth rate of the economy’s net asset position? How does it compare to the equilibrium growth rate of consumption?

5. Suppose that in period 0 the economy unexpectedly experiences a permanent increase in the endowment from $y$ to $y + \Delta y$, with $\Delta y > 0$. Derive the impact response of the trade balance. Briefly discuss your result.

6. Characterize the equilibrium under the assumption that $\gamma = 0$.

## Answer

#### 1.


$$
\max \left\{ \min_{t \geq 0} \left\{ \beta^t c_t \right\} \right\}
$$

subject to

$$
c_t + (1 + r) d_{t-1} = y + d_t
$$

and no Ponzi.

#### 2.

$$
\beta^t c_t = \beta^{t'} c_{t'}
$$

for all $t, t' \geq 0$.

Intertemporal budget constraint:

$$
(1 + r) d_{-1} = \sum_{t=0}^{\infty} \frac{y - c_t}{(1 + r)^t}
$$


#### 3.

$$
c_t = \beta^{-t} c_0.
$$

Lifetime utility then is

$$
\min_{t \geq 0} \left\{ \beta^t (\beta^{-t} c_0) \right\} = c_0.
$$

Pick $c_0$ so that it satisfies the equilibrium intertemporal budget constraint.

Intermediate steps:

$$
\sum_{t=0}^{\infty} \frac{y}{(1 + r)^t} = \frac{1 + r}{r} y
$$

$$
\sum_{t=0}^{\infty} \frac{c_t}{(1 + r)^t} = \sum_{t=0}^{\infty} \frac{c_0}{[\beta(1 + r)]^t} = \sum_{t=0}^{\infty} \frac{c_0}{(1 + \gamma)^t} = \frac{1 + \gamma}{\gamma} c_0
$$

With those intermediate results in hand we can write the eqm intertemporal budget constraint as

$$
(1 + r) d_{-1} = \frac{1 + r}{r} y - \frac{1 + \gamma}{\gamma} c_0
$$

Solve for $c_0$ to obtain:

$$
c_0 = \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right)(y - r d_{-1})
$$

This is the equilibrium value of $c_0$ in terms of $\beta$, $r$, $\gamma$, $y$ and the initial condition $d_{-1}$. And for $t \geq 0$

$$
c_t = \beta^{-t} c_0
$$

With $c_t$ in hand we can find the path of $d_t$. Proceed as follows. For $t = 0$, use the sequential budget constraint and solve for $d_0$, which only requires knowledge of $c_0$, $y$, and $d_{-1}$. Once you know $d_0$, use the sequential budget constraint in $t = 1$ to find $d_1$. Proceed in this way to find the entire sequence of $d_t$. 

#### 4.

The equilibrium intertemporal budget constraint must hold, not just in $t = 0$ but for any period $t \geq 0$. So we have

$$
c_t = \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) (y - r d_{t-1})
$$

Get the change in assets (or minus debt) from sequential budget constraint

$$
c_t + (1 + r) d_{t-1} = y + d_t
$$

Rearrange and then plug the solution for $c_t$ from above

$$
\begin{aligned}
-d_t + d_{t-1} &= y - r d_{t-1} - c_t \\
&= y - r d_{t-1} - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) (y - r d_{t-1}) \\
&= y - r d_{t-1} - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) (y - r d_{t-1}) \\
&= \left[ 1 - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) \right] (y - r d_{t-1}) > 0
\end{aligned}
$$

The term in square parenthesis is positive because $0 < \gamma < r$. For $t = 0$, $y - r d_{-1} > 0$ by assumption. So the current account in period 0 is positive which means that debt declines or equivalently assets go up. Therefore $y - r d_{-1} > 0$ for $t = 1$. But then by induction it is positive for all $t$.

To finance a growing stream of consumption with a fixed endowment income, it must be that debt falls over time. In fact debt turns into assets and then grows without bounds but at a rate less that $r$.

Asymptotically the growth rate of assets ($-d_t$) is

$$
\lim_{t \to \infty} \frac{(-d_t) - (-d_{t-1})}{-d_{t-1}} = \lim_{t \to \infty} \left[ 1 - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) \right] \left( \frac{y - r d_{t-1}}{-d_{t-1}} \right)
= r \left[ 1 - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) \right]
$$

which uses $\lim_{t \to \infty} y / d_{t-1} = 0$ because $-d_{t-1}$ increases without bound.  
The gross growth rate of $-d_t$ is equal to $1 + r \left[ 1 - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) \right] = (1 + r) / (1 + \gamma) < 1 + r$.

The growth rate of consumption is $\beta^{-1} = (1 + r)/(1 + \gamma)$, which is the same as the asymptotic growth rate of assets.

#### 5.

Step 1: Change in consumption in period 0

$$
\Delta c_0 = \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) \Delta y < \Delta y
$$

because $\left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) < 1$.  
This follows from $\beta = (1 + \gamma)/(1 + r) < 1$.  
In words $c_0$ increases but by less than $y$.

Step 2:

$$
\Delta tb_0 = \Delta y - \Delta c_0 = \left[ 1 - \left( \frac{\gamma}{1 + \gamma} \right) \left( \frac{1 + r}{r} \right) \right] \Delta y > 0
$$

This means that a permanent increase in the level of income leads to an increase in the trade balance.  
Under the preferences used in class, namely, time separable and no impatience, we obtained the result that the trade balance was unchanged.  
What is the intuition? With Leontief preferences and agents more patient than the market ($\beta > 1/(1 + \gamma)$) households have an increasing path of consumption over time and to achieve this given that the increase in income is flat (or non-increasing over time), the only way to fund an increasing consumption path is to save more in period 0 and then to use only part of the additional interest income for additional consumption and using the remainder to save.

#### 6.

When $\gamma = 0$, no equilibrium with positive lifetime utility exists.
