---
title: "Exercise 2.18"
subtitle: "Permanent Income Versus Beverage-Nelson Decomposition"
---
<a class="return-button" href="index.qmd">⬅ Return</a>

## Problem

The file `endowment_exercise_Beverage_Nelson.dat` posted online with the materials for the chapter contains a time series for output, which will be denoted $y_t$, for country X. The data is monthly from 1900:1 to 2020:12.

1. Using OLS, estimate the AR(2) process for $\Delta y_t$

    $$
    \Delta y_t = \rho_0 + \rho_1 \Delta y_{t-1} + \rho_2 \Delta y_{t-2} + \epsilon_t. \tag{1}
    $$

    Report the regression results. For the remainder of the exercise, ignore the intercept $\rho_0$.

2. Is the estimated process for $\Delta y_t$ stationary? Show your work.

3. Compute the coefficients of the cyclical component of the Beveridge-Nelson decomposition, which is given by $y^c_t = y_t - \lim_{j \to \infty} \mathbb{E}_t y_{t+j}$.  (Hint: $y^c_t$ is a linear function of $\Delta y_t$ and $\Delta y_{t-1}$.)

4. Make a plot showing $y_t$ and its trend component.  (Hint: Use your answer to the last question and data to construct a time series for $y^c_t$. Then demean $y^c_t$ before subtracting it from $y_t$.)

5. Now compute the coefficients of the permanent component of output according to the open endowment economy model studied in this chapter, which we denoted $y^p_t$. To this end, assume that the world interest rate is 4 percent per year ($r = 1.041^{1/12} - 1$).

6. On the same graph, plot the trend according to the model, $y^p_t$. Comment on any differences you can optically identify about the two ways to compute the trend.

7. According to the open economy model of studied in this chapter, does this estimated endowment process (1) generate a countercyclical current account, as observed in the data?  (Hint: Calculate the effect of a unit increase in $\varepsilon_t$ on $ca_t$, and interpret it.)

8. According to the open economy model studied in this chapter, does the estimated endowment process (1) generate excess consumption volatility? (Hint: Calculate $\sigma_{\Delta c} / \sigma_{\Delta y}$ and provide interpretation.)

## Answer

#### 1.

$$
\begin{array}{l r}
\hline
\Delta y_1 & 0.518 \\
           & (0.026) \\
\Delta y_2 & 0.169 \\
           & (0.026) \\
\text{const.} & 0.000 \\
              & (0.000) \\
\hline
\end{array}
$$

#### 2.

The conditions for AR(2) process stationarity are:  

$$\rho_2 > -1$$  

$$\rho_2 < 1 - \rho_1$$

$$\rho_2 < 1 + \rho_1$$
  
All three conditions are satisfied.

#### 3.

**Begin Answer:**  
After some algebra, the Beveridge–Nelson decomposition can be written as

$$
y_t^c = - \sum_{j=1}^{\infty} E_t \Delta y_{t+j}
$$

Let 
$$
Y_t = \begin{bmatrix} \Delta y_t \\ \Delta y_{t-1} \end{bmatrix}, \quad 
R = \begin{bmatrix} \rho_1 & \rho_2 \\ 1 & 0 \end{bmatrix}
$$

and rewrite the AR(2) process in a matrix form:

$$
Y_t = R Y_{t-1} + \begin{bmatrix} \varepsilon_t \\ 0 \end{bmatrix}
$$

Then 
$$
E_t Y_{t+j} = R^j Y_t
$$ 

and the Beveridge–Nelson cyclical component becomes:

$$
y_t^c = - \begin{bmatrix} 1 & 0 \end{bmatrix} \sum_{j=1}^{\infty} R^j Y_t 
= - \begin{bmatrix} 1 & 0 \end{bmatrix} R (I - R)^{-1} Y_t
$$

Then we can obtain that:

$$
y_t^c = - \frac{1}{1 - \rho_1 - \rho_2} \left( (\rho_1 + \rho_2) \Delta y_t + \rho_2 \Delta y_{t-1} \right)
$$

Coefficients for $y_t^c$:
$$
\begin{array}{l r}
\hline
\Delta y_t       & -2.194 \\
\Delta y_{t-1}   & -0.538 \\
\hline
\end{array}
$$

#### 4.

Run the Stata code `endowment_exercise_Beverage_nelson.do`

Note:`endowment_exercise_Beverage_nelson.do` is currently unavailable.

#### 5.

Recall that:

$$
y_t^p = \frac{r}{1 + r} \sum_{j=0}^{\infty} \frac{E_t y_{t+j}}{(1 + r)^j}
$$

Note that $y_{t+j} = y_t + \sum_{k=1}^j \Delta y_{t+k}$, so the expression above can be written as:

$$
\begin{aligned}
y_t^p &= \frac{r}{1 + r} \sum_{j=0}^{\infty} \frac{y_t + \sum_{k=1}^j E_t \Delta y_{t+k}}{(1 + r)^j} \\
&= y_t + \frac{r}{1 + r} \sum_{j=0}^{\infty} \frac{\sum_{k=1}^j E_t \Delta y_{t+k}}{(1 + r)^j}
\end{aligned}
$$

Recall from the previous sections that $E_t \Delta y_{t+k} = \begin{bmatrix} 1 & 0 \end{bmatrix} R^k Y_t$.  
Remember additionally that the sum of geometric series can be expressed as:

$$
\sum_{k=1}^j E_t \Delta y_{t+k} = \sum_{k=1}^j \begin{bmatrix} 1 & 0 \end{bmatrix} R^k Y_t = \begin{bmatrix} 1 & 0 \end{bmatrix} R (I - R^j)(I - R)^{-1}
$$

Then we can rewrite $y_t^p$ as:

$$
y_t^p = y_t + \frac{r}{1 + r} \sum_{j=0}^{\infty} \frac{\sum_{k=1}^j E_t \Delta y_{t+k}}{(1 + r)^j}
= y_t + \begin{bmatrix} 1 & 0 \end{bmatrix} R(I - R)^{-1} Y_t
+ \begin{bmatrix} 1 & 0 \end{bmatrix} R^2(I - R)^{-1} \sum_{j=0}^{\infty} \frac{R^j}{(1 + r)^j} Y_t
$$

Therefore, permanent income can be expressed as:

$$
y_t^p = y_t + \begin{bmatrix} 1 & 0 \end{bmatrix} R(I - R)^{-1} Y_t
+ \begin{bmatrix} 1 & 0 \end{bmatrix} R^2(I - R)^{-1}(I - R / (1 + r))^{-1} Y_t
$$

Then we can simplify into:

$$
\begin{aligned}
y_t^p = y_t &+ \frac{1}{1 - \rho_1 - \rho_2} \left( (\rho_1 + \rho_2) \Delta y_t + \rho_2 \Delta y_{t-1} \right) \\
&+ \frac{1 + r}{(1 - \rho_1 - \rho_2)(1 + r - \rho_1 - \rho_2)} \left[
((\rho_1 + \rho_2)^2 + \rho_2) \Delta y_t + \left( \rho_1 \rho_2 + \rho_2^2 + \frac{\rho_2^2}{1 + r} \right) \Delta y_{t-1}
\right]
\end{aligned}
$$

Coefficients for $y_t^p$:

$$
\begin{array}{l r}
\hline
\Delta y_t     & 8.681 \\
\Delta y_{t-1} & 1.998 \\
\hline
\end{array}
$$

#### 6.

Run the Stata code `endowment_exercise_Beverage_nelson.do`

Note:`endowment_exercise_Beverage_nelson.do` is currently unavailable.

#### 7.

Recall that:

$$
ca_t = y_t - y^p_t
$$

The effect of $\varepsilon_t$ on the current account is equal to:

$$
ca_t = -\left[
\frac{1}{1 - \rho_1 - \rho_2} (\rho_1 + \rho_2) +
\frac{1 + r}{(1 - \rho_1 - \rho_2)(1 + r - \rho_1 - \rho_2)} ((\rho_1 + \rho_2)^2 + \rho_2)
\right] \varepsilon_t = -\mu \varepsilon_t
$$

Since coefficient is negative, the response of the current account is countercyclical.

#### 8.

Recall that:

$$
\Delta c_t = \Delta y_t^p
$$

Then variance can be written as:

$$
\begin{aligned}
\text{var}(\Delta c_t) &= \text{var}(\Delta y_t^p) \\
&= \text{var}(\Delta y_t + \mu(\Delta y_t - \Delta y_{t-1})) \\
&= (1 + \mu)^2 \, \text{var}(\Delta y_t)
\end{aligned}
$$

$\mu > 0$, therefore, this process generates excess consumption volatility.

